version: '3.8'

services:
  savrm-signal-node:
    image: mirotalk/p2p:latest
    container_name: savrm_resonance_node
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HTTPS=false
      - PROTECT_ROOM=true
